import Layout from "@/components/Layout";
import SpanBeta from "@/components/SpanBeta";
import Head from "next/head";
import styles from '../styles/howtouse.module.css'

export default function HowToUse() {
    return (
        <>
            <Head>
                <title>Image GPT</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <section className={styles.section}>
                    <h1>Como usar?</h1>
                    <div className={styles.container}>
                        <h3 className={styles.titulos}>Gerar imagens:</h3>
                        <p className={styles.p}>Gerar imagens é bastante simples, basta digitar o que deseja ser criado, enviar e após alguns segundos será exibido na tela.</p>

                        <h3 className={styles.titulos}>Criar variações: <SpanBeta /></h3> 
                        <p className={styles.p}>Para criar variações das imagens basta alterar a chave para o modo &quot;variações&quot; e enviar. Nesse modo o prompt será ignorado.</p>

                        <h3 className={styles.titulos}>Editar imagens: <SpanBeta /></h3> 
                        <p className={styles.p}>Para editar uma foto, basta clicar no botão &quot;editar&quot; abaixo das imagens ou alterar a chave para o modo de edição e digitar o que deseja alterar.</p>
                    </div>
                </section>
            </Layout>
        </>
    )
}