import Form from '@/components/Form'
import Head from 'next/head'
import axios from 'axios'
import { useEffect, useState } from 'react'
import ImageList from '@/components/ImageList'
import GeneratedImages from '@/components/GeneratedImages'
import Layout from '@/components/Layout'

export default function Home() {
  const [urlImageFocus, setUrlImageFocus] = useState()
  const [arrayImages, setArrayImages] = useState([])
  const [Loading, setLoading] = useState(false)
   
  async function handleSubmitGen(event) {
    event.preventDefault()
    setLoading(true)
    setArrayImages([...arrayImages, urlImageFocus])
    await axios.post('/api/GenImagem', {prompt: event.target[0].value}).then((response) => {
      setLoading(false)
      setUrlImageFocus(response.data)
    })    
  }

  function handleChangeImage(newUrlImage) {
    // Add the image in focus to array
    let newArray = [...arrayImages, urlImageFocus]

    // Remove the image from the array
    newArray = newArray.filter(url => {
      if(url !== newUrlImage) return url
    })

    setArrayImages(newArray)    
    // Add new image to focus
    setUrlImageFocus(newUrlImage)
  }

  return (
    <>
      <Head>
        <title>Image GPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Form onSubmit={handleSubmitGen}/>

        <GeneratedImages 
          urlImage={urlImageFocus}
          booleanLoading={Loading}
        />

        <ImageList 
          images={arrayImages} 
          onSetImage={handleChangeImage}
        />
      </Layout>
    </>
  )
}
